In [ ]:
# 1
score = 85
if score >= 80:
    print("Grade is A")
elif score >= 80:
    print("Grade is B")
elif score >= 70:
    print("Grade is C")
else:
    print("Grade is D")


Grade is A


In [ ]:
# 2
my_list = [1, 2, 3, 4, 5]
print(my_list[2])
print(my_list[3:5])
my_list[0] = 11
print(my_list)

3
[4, 5]
[11, 2, 3, 4, 5]


In [ ]:
# 3
num1 = 15
num2 = 11

add = num1 + num2
print("The addition of num1 and num2 is:", add)

sub = num1 - num2
print("The subtraction of num1 and num2 is:", sub)

mul = num1 * num2
print("The multiplication of num1 and num2 is:", mul)


The addition of num1 and num2 is: 26
The subtraction of num1 and num2 is: 4
The multiplication of num1 and num2 is: 165


In [ ]:
# 4
num1 = 11
num2 = 24
num3 = 63

if (num1 >= num2) and (num1 >= num3):
    largest = num1
    print("Largest number is:", largest)
elif (num2 >= num1) and (num2 >= num3):
    largest = num2
    print("Largest number is:", largest)
else:
    largest = num3
    print("Largest number is:", largest)

Largest number is: 63


In [ ]:
# 5

def square(x):
  return x**2

def cube(x):
  return x**2


def transform(f,L):
  output = []
  for i in L:
    output.append(f(i))

  print(output)

L = [1,2,3,4,5]

transform(cube,L)

[1, 4, 9, 16, 25]


In [ ]:
# 6
def calculator():
    print("Select operation:")
    print("1. Add")
    print("2. Subtract")
    print("3. Multiply")
    print("4. Divide")

    choice = input("Enter choice (1/2/3/4): ")

    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))

    if choice == '1':
        print(f"{num1} + {num2} = {num1 + num2}")
    elif choice == '2':
        print(f"{num1} - {num2} = {num1 - num2}")
    elif choice == '3':
        print(f"{num1} * {num2} = {num1 * num2}")
    elif choice == '4':
        if num2 != 0:
            print(f"{num1} / {num2} = {num1 / num2}")
        else:
            print("Error! Division by zero.")
    else:
        print("Invalid input")

calculator()


Select operation:
1. Add
2. Subtract
3. Multiply
4. Divide
Enter choice (1/2/3/4): 3
Enter first number: 5
Enter second number: 6
5.0 * 6.0 = 30.0


In [15]:
# 7
class Person:
    def __init__(self,name,age):
        self.name=name
        self.age=age

    def introduce(self):
        print(f"Name is : {self.name}, and age is : {self.age}")


In [16]:
person1=Person("nitin","17")
person1.introduce()


Name is : nitin, and age is : 17


In [20]:
# 8
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [24]:
# 9
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9,10,11,12,13,14,15,16,17,18,19,20])

x = np.where(arr%2 == 0)

print(x)

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]),)


In [27]:
# 10
from numpy import random

x = random.choice([3, 5, 7, 9], size=(4, 6))

print(x)


[[7 7 7 3 7 7]
 [5 3 5 7 7 9]
 [3 9 5 5 5 3]
 [5 7 3 3 7 5]]


In [45]:
# 11
import pandas as pd

mydataset = {
  'cars': ["balano", "nano", "i20"],
  'passings': [3, 7, 3]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

     cars  passings
0  balano         3
1    nano         7
2     i20         3


In [52]:
# 12
for num in range(2, 17):
    is_prime = True
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            is_prime = False
            break
    if is_prime:
        print(num, "is a prime number")
    else:
        print(num, "is not a prime number")

2 is a prime number
3 is a prime number
4 is not a prime number
5 is a prime number
6 is not a prime number
7 is a prime number
8 is not a prime number
9 is not a prime number
10 is not a prime number
11 is a prime number
12 is not a prime number
13 is a prime number
14 is not a prime number
15 is not a prime number
16 is not a prime number


In [57]:
# 13
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [59]:
# 14
import numpy as np

arr = np.array([11,22,33,44,55])

filter_arr = []

for element in arr:
  if element > 22:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False, False, True, True, True]
[33 44 55]


In [60]:
# 15
!pip install pandas

In [61]:
df = pd.read_csv('/content/covid_impact_on_work new.csv')

In [64]:
print(df)

     Stress_Level     Sector  Increased_Work_Hours  Work_From_Home  \
0             Low     Retail                     1               1   
1             Low         IT                     1               1   
2          Medium     Retail                     1               0   
3          Medium  Education                     1               1   
4          Medium  Education                     0               1   
...           ...        ...                   ...             ...   
9995       Medium         IT                     1               1   
9996       Medium         IT                     0               0   
9997          Low     Retail                     1               1   
9998       Medium  Education                     1               1   
9999       Medium     Retail                     0               0   

        Hours_Worked_Per_Day        Meetings_Per_Day  Productivity_Change  \
0      6.392.393.639.805.820  26.845.944.014.488.700                    1   
1    

In [68]:
# 16
!pip install pandas

In [69]:
df = pd.read_csv('/content/gym_members_exercise_tracking.csv')

In [70]:
print(df)

     Age  Gender  Weight (kg)  Height (m)  Max_BPM  Avg_BPM  Resting_BPM  \
0     56    Male         88.3        1.71      180      157           60   
1     46  Female         74.9        1.53      179      151           66   
2     32  Female         68.1        1.66      167      122           54   
3     25    Male         53.2        1.70      190      164           56   
4     38    Male         46.1        1.79      188      158           68   
..   ...     ...          ...         ...      ...      ...          ...   
968   24    Male         87.1        1.74      187      158           67   
969   25    Male         66.6        1.61      184      166           56   
970   59  Female         60.4        1.76      194      120           53   
971   32    Male        126.4        1.83      198      146           62   
972   46    Male         88.7        1.63      166      146           66   

     Session_Duration (hours)  Calories_Burned Workout_Type  Fat_Percentage  \
0       